# Copyright (c) 2026 Tom Stryhn. Licensed under CC BY-NC 4.0.

#Requires -Version 5.1
<#
.SYNOPSIS
    Assembles the DummyLab 1.0.0 module from source.

.DESCRIPTION
    Concatenates src/DummyLab/Private and src/DummyLab/Public .ps1 files into
    a single DummyLab.psm1. Copies the manifest, format file, and bundled
    defaults config into the assembled module directory. The output module
    is loadable with Import-Module.

    Source layout:
        src/DummyLab/
            DummyLab.psd1
            Config/DLab.Defaults.psd1
            Formats/DummyLab.Format.ps1xml
            Private/*.ps1
            Public/*.ps1

    Output layout (Modules/DummyLab/):
        DummyLab.psd1
        DummyLab.psm1          <- assembled
        DummyLab.Format.ps1xml <- copied
        DLab.Defaults.psd1     <- copied

.PARAMETER Validate
    Parse-check the assembled .psm1 after building.

.PARAMETER Clean
    Remove the output directory before building.

.EXAMPLE
    .\Build-DummyLab.ps1 -Validate
#>
[CmdletBinding()]
param(
    [switch]$Validate,
    [switch]$Clean
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$projectRoot = $PSScriptRoot
$srcRoot     = Join-Path $projectRoot 'src\DummyLab'
$outRoot     = Join-Path $projectRoot 'Modules\DummyLab'

if (-not (Test-Path $srcRoot)) {
    throw "Source not found: $srcRoot"
}

if ($Clean -and (Test-Path $outRoot)) {
    Write-Host "  [~] Cleaning $outRoot" -ForegroundColor DarkGray
    Remove-Item -Path $outRoot -Recurse -Force
}
if (-not (Test-Path $outRoot)) {
    New-Item -ItemType Directory -Path $outRoot -Force | Out-Null
}

Write-Host ""
Write-Host "  Dummy.Lab 1.0.0 - Module Build" -ForegroundColor Cyan
Write-Host "  Source : $srcRoot"
Write-Host "  Output : $outRoot"
Write-Host ""

# Collect source
$privateFiles = @(Get-ChildItem -Path (Join-Path $srcRoot 'Private') -Filter '*.ps1' -ErrorAction SilentlyContinue | Sort-Object Name)
$publicFiles  = @(Get-ChildItem -Path (Join-Path $srcRoot 'Public')  -Filter '*.ps1' -ErrorAction SilentlyContinue | Sort-Object Name)

if ($publicFiles.Count -eq 0) {
    throw "No public .ps1 files found in $srcRoot/Public"
}

function Get-FunctionNames {
    param([System.IO.FileInfo[]]$Files)
    $names = @()
    foreach ($f in $Files) {
        $content = Get-Content $f.FullName -Raw
        if ($content -match 'function\s+([A-Za-z][\w-]+)\s*\{') {
            $names += $matches[1]
        }
    }
    return $names
}

$publicNames = Get-FunctionNames -Files $publicFiles
$privateNames = Get-FunctionNames -Files $privateFiles

# Assemble psm1
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("#Requires -Version 5.1")
$lines.Add("<#")
$lines.Add(".SYNOPSIS")
$lines.Add("    DummyLab - assembled module.")
$lines.Add("")
$lines.Add(".NOTES")
$lines.Add("    DO NOT EDIT THIS FILE DIRECTLY.")
$lines.Add("    Edit individual functions under src/DummyLab/")
$lines.Add("    Then run: .\Build-DummyLab.ps1")
$lines.Add("    Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$lines.Add("#>")
$lines.Add("")
$lines.Add("Set-StrictMode -Version Latest")
$lines.Add("")

# Private first (parse-order-safe, but private before public matches convention)
if ($privateFiles.Count -gt 0) {
    $lines.Add("#region Private")
    foreach ($f in $privateFiles) {
        $fnName = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
        $lines.Add("")
        $lines.Add("#region $fnName")
        $lines.Add((Get-Content $f.FullName -Raw).TrimEnd())
        $lines.Add("#endregion $fnName")
    }
    $lines.Add("")
    $lines.Add("#endregion Private")
    $lines.Add("")
}

# Public
$lines.Add("#region Public")
foreach ($f in $publicFiles) {
    $fnName = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    $lines.Add("")
    $lines.Add("#region $fnName")
    $lines.Add((Get-Content $f.FullName -Raw).TrimEnd())
    $lines.Add("#endregion $fnName")
}
$lines.Add("")
$lines.Add("#endregion Public")
$lines.Add("")

# Export list
$lines.Add("#region Exports")
$lines.Add("Export-ModuleMember -Function @(")
$lines.Add((($publicNames | ForEach-Object { "    '$_'" }) -join ",`n"))
$lines.Add(")")
$lines.Add("#endregion Exports")
$lines.Add("")

$psm1Path = Join-Path $outRoot 'DummyLab.psm1'
$lines -join "`n" | Set-Content -Path $psm1Path -Encoding UTF8

# Copy manifest, formats, defaults
Copy-Item -Path (Join-Path $srcRoot 'DummyLab.psd1')                     -Destination (Join-Path $outRoot 'DummyLab.psd1')         -Force
Copy-Item -Path (Join-Path $srcRoot 'Formats\DummyLab.Format.ps1xml')    -Destination (Join-Path $outRoot 'DummyLab.Format.ps1xml') -Force
Copy-Item -Path (Join-Path $srcRoot 'Config\DLab.Defaults.psd1')         -Destination (Join-Path $outRoot 'DLab.Defaults.psd1')     -Force

$lineCount = (Get-Content $psm1Path).Count
Write-Host "  [OK] DummyLab.psm1    ($($publicFiles.Count) public, $($privateFiles.Count) private, $lineCount lines)" -ForegroundColor Green
Write-Host "  [OK] DummyLab.psd1    (manifest)" -ForegroundColor Green
Write-Host "  [OK] DummyLab.Format.ps1xml" -ForegroundColor Green
Write-Host "  [OK] DLab.Defaults.psd1" -ForegroundColor Green

# Validate. Failures throw so calling scripts (Install-Dummy.Lab.ps1) can catch
# via try/catch. `exit 1` would only set $LASTEXITCODE and silently return
# control to the caller.
if ($Validate) {
    Write-Host ""
    Write-Host "  Validating..." -ForegroundColor Cyan
    $errors = $null
    $null = [System.Management.Automation.Language.Parser]::ParseFile($psm1Path, [ref]$null, [ref]$errors)
    if ($errors -and $errors.Count -gt 0) {
        Write-Host "  [!!] Syntax errors in $psm1Path" -ForegroundColor Red
        foreach ($e in $errors) {
            Write-Host "      Line $($e.Extent.StartLineNumber): $($e.Message)" -ForegroundColor Red
        }
        throw "DummyLab .psm1 has $($errors.Count) syntax error(s). See above."
    }
    Write-Host "  [OK] Syntax OK" -ForegroundColor Green

    try {
        $null = Test-ModuleManifest -Path (Join-Path $outRoot 'DummyLab.psd1') -ErrorAction Stop
        Write-Host "  [OK] Manifest OK" -ForegroundColor Green
    } catch {
        Write-Host "  [!!] Manifest check failed: $($_.Exception.Message)" -ForegroundColor Red
        throw "DummyLab manifest failed Test-ModuleManifest: $($_.Exception.Message)"
    }
}

Write-Host ""
Write-Host "  Module ready at: $outRoot" -ForegroundColor Green
Write-Host "  Load with:       Import-Module '$outRoot\DummyLab.psd1' -Force" -ForegroundColor DarkGray
Write-Host ""
